### ISSUE TITLE
Revolut statement parser is broken

### ISSUE THREAD

**Issue by mikeus-hanzlik** [vladimir-aubrecht/StatementParser#16]
Revolut statements from 2021 are not compatible with existing parser. Format of statements probably changed.

**Comment by vladimir-aubrecht** [comment]
I added parser for Csv which Revolut can generate now. It will be more reliable for future. I kept old parser intact in case somebody is storing old pdfs ...

Also added support for SaleTransactions parsing :)

It's in this [commit](https://github.com/vladimir-aubrecht/StatementParser/commit/556f0930b253ee94cd758071d6be4d60caa4b402), seems working but I'd like to get to additional review in couple of days and improve also logging which is currently annoying...

**Comment by vladimir-aubrecht** [comment]
Fixed in version 1.8.
